// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlgmJ-L3JePnDrRMqQg_FO0j3p5rCfA10',
    appId: '1:67847332359:web:d93b142d5f75a160c980a2',
    messagingSenderId: '67847332359',
    projectId: 'blogbox-bba7f',
    authDomain: 'blogbox-bba7f.firebaseapp.com',
    storageBucket: 'blogbox-bba7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXUkHgVZomFoSPMybodKddXIntU_icEE',
    appId: '1:67847332359:android:ef6dd262cf08579dc980a2',
    messagingSenderId: '67847332359',
    projectId: 'blogbox-bba7f',
    storageBucket: 'blogbox-bba7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt9rKDeSeDAM6Sv0Ks3BNJibXKsLHMiYk',
    appId: '1:67847332359:ios:45e3876234e45db6c980a2',
    messagingSenderId: '67847332359',
    projectId: 'blogbox-bba7f',
    storageBucket: 'blogbox-bba7f.appspot.com',
    iosBundleId: 'com.example.blogbox',
  );
}
